packages:
  - apps/*
  - packages/**/*

catalogs:
  eslint:
    '@eslint/js': ^9.31.0
    '@stylistic/eslint-plugin': ^5.6.1
    eslint: ^9.31.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-jsdoc: ^61.4.1
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-unused-imports: ^4.1.4
    globals: ^16.3.0
  prettier:
    '@prettier/plugin-xml': ^3.4.2
  react19:
    '@eslint-react/eslint-plugin': ^2.0.0
    '@types/react': ^19.2.2
    '@types/react-dom': ^19.2.1
    babel-plugin-react-compiler: ^1.0.0
    eslint-plugin-react-hooks: ^7.0.0
    eslint-plugin-react-refresh: ^0.4.20
    react: ^19.2.0
    react-dom: ^19.2.0
  tanstackAi:
    '@tanstack/ai': ^0.5.1
    '@tanstack/ai-anthropic': ^0.5.0
    '@tanstack/ai-client': ^0.4.5
    '@tanstack/ai-gemini': ^0.8.6
    '@tanstack/ai-openai': ^0.5.0
    '@tanstack/ai-react': ^0.5.4
    '@tanstack/react-ai-devtools': ^0.2.8
  tanstackQuery:
    '@tanstack/eslint-plugin-query': ^5.99.0
    '@tanstack/react-query': ^5.99.0
    '@tanstack/react-query-devtools': ^5.99.0
  tanstackStart:
    '@tanstack/eslint-plugin-router': ^1.161.6
    '@tanstack/react-router': ^1.168.22
    '@tanstack/react-router-devtools': ^1.166.13
    '@tanstack/react-router-ssr-query': ^1.166.11
    '@tanstack/react-start': ^1.167.41
    '@tanstack/router-plugin': ^1.167.22
  ts5:
    typescript: ^5.8.3
    typescript-eslint: ^8.37.0
  zod4:
    zod: ^4.1.12

linkWorkspacePackages: true

preferWorkspacePackages: true
