import { IconType } from 'react-icons'
import {
	FaAngular,
	FaCss3,
	FaDocker,
	FaGithub,
	FaHtml5,
	FaJava,
	FaJs,
	FaLaravel,
	FaLess,
	FaMarkdown,
	FaNodeJs,
	FaPhp,
	FaPython,
	FaReact,
	FaSass,
	FaUnity,
	FaVuejs,
} from 'react-icons/fa'
import {
	SiChakraui,
	SiCsharp,
	SiDart,
	SiDjango,
	SiExpress,
	SiFastapi,
	SiFirebase,
	SiFlask,
	SiFlutter,
	SiGo,
	SiHaskell,
	SiHeroku,
	SiJinja,
	SiJquery,
	SiJupyter,
	SiKotlin,
	SiLatex,
	SiMariadb,
	SiMongodb,
	SiMysql,
	SiNextdotjs,
	SiNginx,
	SiNumpy,
	SiPostgresql,
	SiPrisma,
	SiSvelte,
	SiSvg,
	SiSwift,
	SiTailwindcss,
	SiTypescript,
} from 'react-icons/si'
import { VscJson, VscRegex, VscCode } from 'react-icons/vsc'

export const Icons: Record<string, IconType> = {
	angular: FaAngular,
	c: VscCode,
	'c#': SiCsharp,
	'c++': VscCode,
	chakra: SiChakraui,
	css: FaCss3,
	cuda: VscCode,
	dart: SiDart,
	django: SiDjango,
	docker: FaDocker,
	express: SiExpress,
	fastapi: SiFastapi,
	firebase: SiFirebase,
	flask: SiFlask,
	flutter: SiFlutter,
	github: FaGithub,
	go: SiGo,
	haskell: SiHaskell,
	html: FaHtml5,
	http: VscCode,
	java: FaJava,
	javascript: FaJs,
	jinja: SiJinja,
	jquery: SiJquery,
	json: VscJson,
	jupyter: SiJupyter,
	kotlin: SiKotlin,
	laravel: FaLaravel,
	less: FaLess,
	makefile: VscCode,
	mariadb: SiMariadb,
	markdown: FaMarkdown,
	matlab: VscCode,
	mongodb: SiMongodb,
	mysql: SiMysql,
	nextjs: SiNextdotjs,
	nginx: SiNginx,
	nodejs: FaNodeJs,
	numpy: SiNumpy,
	php: FaPhp,
	postgresql: SiPostgresql,
	prisma: SiPrisma,
	procfile: SiHeroku,
	prolog: VscCode,
	python: FaPython,
	react: FaReact,
	regex: VscRegex,
	sass: FaSass,
	scss: VscCode,
	svelte: SiSvelte,
	svg: SiSvg,
	swift: SiSwift,
	tailwindcss: SiTailwindcss,
	tex: SiLatex,
	typescript: SiTypescript,
	unity: FaUnity,
	vue: FaVuejs,
	xml: VscCode,
	yaml: VscCode,
}
