import 'server-only';

import type { TechStack } from '@/app/_libs/_common/_models/tech-stack.model';

import type { IconType } from './icon.prop.type';

import {
  SiAngular,
  SiC,
  SiChakraui,
  SiCplusplus,
  SiCsharp,
  SiCss3,
  SiCssmodules,
  SiDart,
  SiDjango,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiGo,
  SiHtml5,
  SiJavascript,
  SiMariadb,
  SiMui,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNodedotjs,
  SiPhp,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiReactquery,
  SiRedux,
  SiSimpleicons,
  SiStyledcomponents,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
} from '@icons-pack/react-simple-icons';

const Icon: Record<'default' | TechStack['icon'], IconType> = {
  angular: SiAngular,
  c: SiC,
  'chakra-ui': SiChakraui,
  cpp: SiCplusplus,
  csharp: SiCsharp,
  css3: SiCss3,
  cssmodules: SiCssmodules,
  dart: SiDart,
  default: SiSimpleicons,
  django: SiDjango,
  express: SiExpress,
  fastapi: SiFastapi,
  firebase: SiFirebase,
  flask: SiFlask,
  go: SiGo,
  html5: SiHtml5,
  javascript: SiJavascript,
  mariadb: SiMariadb,
  mui: SiMui,
  mysql: SiMysql,
  nestjs: SiNestjs,
  'next.js': SiNextdotjs,
  'node.js': SiNodedotjs,
  php: SiPhp,
  postgresql: SiPostgresql,
  prisma: SiPrisma,
  python: SiPython,
  react: SiReact,
  'react-query': SiReactquery,
  redux: SiRedux,
  'styled-components': SiStyledcomponents,
  tailwindcss: SiTailwindcss,
  typescript: SiTypescript,
  vercel: SiVercel,
};

export default Icon;
