import './globals.css';

import type { Metadata } from 'next';

import { Inter } from 'next/font/google';
import { twMerge } from 'tailwind-merge';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, 'flex flex-col')}>
        <nav
          className={twMerge(
            'fixed left-0 top-0 right-0',
            'flex justify-center',
            'lg:border border-b border-gray-300 dark:border-neutral-800 lg:rounded-xl',
            'backdrop-blur-2xl',
            'bg-gradient-to-b dark:from-inherit from-zinc-200 dark:bg-zinc-800/30 lg:dark:bg-zinc-800/30',
            'py-8 lg:p-4',
          )}
        >
          Get started by editing&nbsp;
          <code className="font-mono font-bold">app/page.tsx</code>
        </nav>
        <main className="pt-24 pb-32">{children}</main>
        <footer
          className={twMerge(
            'h-32 w-full',
            'flex items-end justify-center',
            'fixed bottom-0 left-0 right-0',
            'bg-gradient-to-t from-white via-white dark:from-black dark:via-black',
            'pb-5',
          )}
        >
          &copy; Hokki Suwanda
        </footer>
      </body>
    </html>
  );
}
