import {
	FaAngular,
	FaCss3,
	FaDocker,
	FaGithub,
	FaHtml5,
	FaJava,
	FaJs,
	FaLaravel,
	FaLess,
	FaMarkdown,
	FaNodeJs,
	FaPhp,
	FaPython,
	FaReact,
	FaSass,
	FaUnity,
	FaVuejs,
} from 'react-icons/fa'
import {
	SiCsharp,
	SiDart,
	SiDjango,
	SiFastapi,
	SiFirebase,
	SiHaskell,
	SiHeroku,
	SiJinja,
	SiJquery,
	SiJupyter,
	SiKotlin,
	SiLatex,
	SiMysql,
	SiNextdotjs,
	SiNginx,
	SiNumpy,
	SiPrisma,
	SiSvelte,
	SiSvg,
	SiSwift,
	SiTypescript,
} from 'react-icons/si'
import { VscJson, VscRegex } from 'react-icons/vsc'

// 		c: '#555555',
// 		'c++': '#f34b7d',
// 		cuda: '#3a4e3a',
// 		http: '#005c9c',
// 		makefile: '#427819',
// 		matlab: '#e16737',
// 		prolog: '#74283c',
// 		scss: '#c6538c',
// 		xml: '#0060ac',
// 		yaml: '#cb171e',
export const Icons = {
	angular: FaAngular,
	'c#': SiCsharp,
	css: FaCss3,
	dart: SiDart,
	django: SiDjango,
	docker: FaDocker,
	fastapi: SiFastapi,
	firebase: SiFirebase,
	github: FaGithub,
	haskell: SiHaskell,
	html: FaHtml5,
	java: FaJava,
	javascript: FaJs,
	jinja: SiJinja,
	jquery: SiJquery,
	json: VscJson,
	jupyter: SiJupyter,
	kotlin: SiKotlin,
	laravel: FaLaravel,
	less: FaLess,
	markdown: FaMarkdown,
	mysql: SiMysql,
	nextjs: SiNextdotjs,
	nginx: SiNginx,
	nodejs: FaNodeJs,
	numpy: SiNumpy,
	php: FaPhp,
	prisma: SiPrisma,
	procfile: SiHeroku,
	python: FaPython,
	react: FaReact,
	regex: VscRegex,
	sass: FaSass,
	svelte: SiSvelte,
	svg: SiSvg,
	swift: SiSwift,
	tex: SiLatex,
	typescript: SiTypescript,
	unity: FaUnity,
	vue: FaVuejs,
}
