[build]
  command = "pnpm --filter @portfolio/fe3h-calculator... run build"
  publish = "apps/fe3h-calculator/dist/client"
  base = "/"

[functions]
  directory = "apps/fe3h-calculator/.netlify/v1/functions"
