import * as React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { Collapse, Loading, Tag } from '~/elements'
import { UnderDevelopment } from '~/modules'

const Skills: NextPage = () => {
	return <UnderDevelopment />

	return (
		<React.Fragment>
			<Head>
				<title>About · hokkyss</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
		</React.Fragment>
	)
}

export default Skills
