import * as React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import {
	Avatar,
	Center,
	Image as ChakraImage,
	ImageProps,
} from '@chakra-ui/react'

import { useBreakpointValue } from '~/hooks'

const Home: NextPage = () => {
	const value = useBreakpointValue<ImageProps['boxSize']>({
		base: '40',
		sm: '40',
		md: '48',
		lg: '3xs',
	})

	return (
		<React.Fragment>
			<Head>
				<title>Hokki Suwanda</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Center
				flexDirection="column"
				justifyContent="center"
				alignItems="center"
			>
				<ChakraImage
					borderRadius="full"
					bg="transparent"
					src="me.png"
					title="Hokki Suwanda"
					boxSize={value}
					fallback={<Avatar width={value} height={value} />}
				/>
			</Center>
		</React.Fragment>
	)
}

export default Home
