import * as React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Avatar, AvatarProps, Box } from '@chakra-ui/react'

import { useBreakpointValue } from '~/hooks'

const Home: NextPage = () => {
	const value = useBreakpointValue<AvatarProps['size']>({
		base: 'xl',
		sm: 'xl',
		md: '2xl',
		lg: '2xl',
	})

	return (
		<React.Fragment>
			<Head>
				<title>Hokki Suwanda</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Box>
				<Avatar
					size={value}
					bg="transparent"
					name="Hokki Suwanda"
					src="me.png"
				></Avatar>
			</Box>
		</React.Fragment>
	)
}

export default Home
