import * as React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { useSkills } from '~/api/firebase'
import { Collapse, Loading, Tag } from '~/elements'
import { UnderDevelopment } from '~/modules'

const Skills: NextPage = () => {
	const { skills, loaded } = useSkills()

	return <UnderDevelopment />

	return (
		<React.Fragment>
			<Head>
				<title>Hokki Suwanda</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			{!loaded ? (
				<Loading />
			) : (
				<React.Fragment>
					<Collapse title="Programming Language">
						{skills.languages.map((l) => (
							<Tag key={l} tag={l} />
						))}
					</Collapse>
					<Collapse title="Frameworks and Libraries">
						{skills.frameworks.map((f) => (
							<Tag key={f} tag={f} />
						))}
					</Collapse>
					<Collapse title="Databases">
						{skills.databases.map((d) => (
							<Tag key={d} tag={d} />
						))}
					</Collapse>
				</React.Fragment>
			)}
		</React.Fragment>
	)
}

export default Skills
