import * as React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

const Skills: NextPage = () => {
	return (
		<React.Fragment>
			<Head>
				<title>Hokki Suwanda</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			Skills
		</React.Fragment>
	)
}

export default Skills
