/**
 * @see {@link https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/metadata/types/metadata-interface.ts#L697 Source}
 */
export type Sitemap = Array<{
  alternates?:
    | {
      languages?: SitemapLanguages<string> | undefined;
    }
    | undefined;
  changeFrequency?:
    | 'always'
    | 'daily'
    | 'hourly'
    | 'monthly'
    | 'never'
    | 'weekly'
    | 'yearly'
    | undefined;
  images?: string[] | undefined;
  lastModified?: Date | string | undefined;
  priority?: number | undefined;
  url: string;
  videos?: SitemapVideo[] | undefined;
}>;

type HrefLang = LangCode | UnmatchedLang;

type LangCode
  = | 'aa'
    | 'ab'
    | 'ae'
    | 'af-ZA'
    | 'af'
    | 'ak'
    | 'am-ET'
    | 'am'
    | 'an'
    | 'ar-AE'
    | 'ar-BH'
    | 'ar-DZ'
    | 'ar-EG'
    | 'ar-IQ'
    | 'ar-JO'
    | 'ar-KW'
    | 'ar-LB'
    | 'ar-LY'
    | 'ar-MA'
    | 'ar-OM'
    | 'ar-QA'
    | 'ar-SA'
    | 'ar-SD'
    | 'ar-SY'
    | 'ar-TN'
    | 'ar-YE'
    | 'ar'
    | 'arn-CL'
    | 'as-IN'
    | 'as'
    | 'av'
    | 'ay'
    | 'az-az'
    | 'az-Cyrl-AZ'
    | 'az-Latn-AZ'
    | 'az'
    | 'ba-RU'
    | 'ba'
    | 'be-BY'
    | 'be'
    | 'bg-BG'
    | 'bg'
    | 'bh'
    | 'bi'
    | 'bm'
    | 'bn-BD'
    | 'bn-IN'
    | 'bn'
    | 'bo-CN'
    | 'bo'
    | 'br-FR'
    | 'br'
    | 'bs-Cyrl-BA'
    | 'bs-Latn-BA'
    | 'bs'
    | 'ca-ES'
    | 'ca'
    | 'ce'
    | 'ch'
    | 'co-FR'
    | 'co'
    | 'cr'
    | 'cs-CZ'
    | 'cs'
    | 'cu'
    | 'cv'
    | 'cy-GB'
    | 'cy'
    | 'da-DK'
    | 'da'
    | 'de-AT'
    | 'de-CH'
    | 'de-DE'
    | 'de-LI'
    | 'de-LU'
    | 'de'
    | 'dsb-DE'
    | 'dv-MV'
    | 'dv'
    | 'dz'
    | 'ee'
    | 'el-CY'
    | 'el-GR'
    | 'el'
    | 'en-029'
    | 'en-AU'
    | 'en-BZ'
    | 'en-CA'
    | 'en-cb'
    | 'en-GB'
    | 'en-IE'
    | 'en-IN'
    | 'en-JM'
    | 'en-MT'
    | 'en-MY'
    | 'en-NZ'
    | 'en-PH'
    | 'en-SG'
    | 'en-TT'
    | 'en-US'
    | 'en-ZA'
    | 'en-ZW'
    | 'en'
    | 'eo'
    | 'es-AR'
    | 'es-BO'
    | 'es-CL'
    | 'es-CO'
    | 'es-CR'
    | 'es-DO'
    | 'es-EC'
    | 'es-ES'
    | 'es-GT'
    | 'es-HN'
    | 'es-MX'
    | 'es-NI'
    | 'es-PA'
    | 'es-PE'
    | 'es-PR'
    | 'es-PY'
    | 'es-SV'
    | 'es-US'
    | 'es-UY'
    | 'es-VE'
    | 'es'
    | 'et-EE'
    | 'et'
    | 'eu-ES'
    | 'eu'
    | 'fa-IR'
    | 'fa'
    | 'ff'
    | 'fi-FI'
    | 'fi'
    | 'fil-PH'
    | 'fj'
    | 'fo-FO'
    | 'fo'
    | 'fr-BE'
    | 'fr-CA'
    | 'fr-CH'
    | 'fr-FR'
    | 'fr-LU'
    | 'fr-MC'
    | 'fr'
    | 'fy-NL'
    | 'fy'
    | 'ga-IE'
    | 'ga'
    | 'gd-GB'
    | 'gd-ie'
    | 'gd'
    | 'gl-ES'
    | 'gl'
    | 'gn'
    | 'gsw-FR'
    | 'gu-IN'
    | 'gu'
    | 'gv'
    | 'ha-Latn-NG'
    | 'ha'
    | 'he-IL'
    | 'he'
    | 'hi-IN'
    | 'hi'
    | 'ho'
    | 'hr-BA'
    | 'hr-HR'
    | 'hr'
    | 'hsb-DE'
    | 'ht'
    | 'hu-HU'
    | 'hu'
    | 'hy-AM'
    | 'hy'
    | 'hz'
    | 'ia'
    | 'id-ID'
    | 'id'
    | 'ie'
    | 'ig-NG'
    | 'ig'
    | 'ii-CN'
    | 'ii'
    | 'ik'
    | 'in-ID'
    | 'io'
    | 'is-IS'
    | 'is'
    | 'it-CH'
    | 'it-IT'
    | 'it'
    | 'iu-Cans-CA'
    | 'iu-Latn-CA'
    | 'iu'
    | 'iw-IL'
    | 'ja-JP'
    | 'ja'
    | 'jv'
    | 'ka-GE'
    | 'ka'
    | 'kg'
    | 'ki'
    | 'kj'
    | 'kk-KZ'
    | 'kk'
    | 'kl-GL'
    | 'kl'
    | 'km-KH'
    | 'km'
    | 'kn-IN'
    | 'kn'
    | 'ko-KR'
    | 'ko'
    | 'kok-IN'
    | 'kr'
    | 'ks'
    | 'ku'
    | 'kv'
    | 'kw'
    | 'ky-KG'
    | 'ky'
    | 'la'
    | 'lb-LU'
    | 'lb'
    | 'lg'
    | 'li'
    | 'ln'
    | 'lo-LA'
    | 'lo'
    | 'lt-LT'
    | 'lt'
    | 'lu'
    | 'lv-LV'
    | 'lv'
    | 'mg'
    | 'mh'
    | 'mi-NZ'
    | 'mi'
    | 'mk-MK'
    | 'mk'
    | 'ml-IN'
    | 'ml'
    | 'mn-MN'
    | 'mn-Mong-CN'
    | 'mn'
    | 'moh-CA'
    | 'mr-IN'
    | 'mr'
    | 'ms-BN'
    | 'ms-MY'
    | 'ms'
    | 'mt-MT'
    | 'mt'
    | 'my'
    | 'na'
    | 'nb-NO'
    | 'nb'
    | 'nd'
    | 'ne-NP'
    | 'ne'
    | 'ng'
    | 'nl-BE'
    | 'nl-NL'
    | 'nl'
    | 'nn-NO'
    | 'nn'
    | 'no-no'
    | 'no'
    | 'nr'
    | 'nso-ZA'
    | 'nv'
    | 'ny'
    | 'oc-FR'
    | 'oc'
    | 'oj'
    | 'om'
    | 'or-IN'
    | 'or'
    | 'os'
    | 'pa-IN'
    | 'pa'
    | 'pi'
    | 'pl-PL'
    | 'pl'
    | 'prs-AF'
    | 'ps-AF'
    | 'ps'
    | 'pt-BR'
    | 'pt-PT'
    | 'pt'
    | 'qu'
    | 'qut-GT'
    | 'quz-BO'
    | 'quz-EC'
    | 'quz-PE'
    | 'rm-CH'
    | 'rm'
    | 'rn'
    | 'ro-mo'
    | 'ro-RO'
    | 'ro'
    | 'ru-mo'
    | 'ru-RU'
    | 'ru'
    | 'rw-RW'
    | 'rw'
    | 'sa-IN'
    | 'sa'
    | 'sah-RU'
    | 'sc'
    | 'sd'
    | 'se-FI'
    | 'se-NO'
    | 'se-SE'
    | 'se'
    | 'sg'
    | 'si-LK'
    | 'si'
    | 'sk-SK'
    | 'sk'
    | 'sl-SI'
    | 'sl'
    | 'sm'
    | 'sma-NO'
    | 'sma-SE'
    | 'smj-NO'
    | 'smj-SE'
    | 'smn-FI'
    | 'sms-FI'
    | 'sn'
    | 'so'
    | 'sq-AL'
    | 'sq'
    | 'sr-BA'
    | 'sr-CS'
    | 'sr-Cyrl-BA'
    | 'sr-Cyrl-CS'
    | 'sr-Cyrl-ME'
    | 'sr-Cyrl-RS'
    | 'sr-Latn-BA'
    | 'sr-Latn-CS'
    | 'sr-Latn-ME'
    | 'sr-Latn-RS'
    | 'sr-ME'
    | 'sr-RS'
    | 'sr-sp'
    | 'sr'
    | 'ss'
    | 'st'
    | 'su'
    | 'sv-FI'
    | 'sv-SE'
    | 'sv'
    | 'sw-KE'
    | 'sw'
    | 'syr-SY'
    | 'ta-IN'
    | 'ta'
    | 'te-IN'
    | 'te'
    | 'tg-Cyrl-TJ'
    | 'tg'
    | 'th-TH'
    | 'th'
    | 'ti'
    | 'tk-TM'
    | 'tk'
    | 'tl'
    | 'tlh-QS'
    | 'tn-ZA'
    | 'tn'
    | 'to'
    | 'tr-TR'
    | 'tr'
    | 'ts'
    | 'tt-RU'
    | 'tt'
    | 'tw'
    | 'ty'
    | 'tzm-Latn-DZ'
    | 'ug-CN'
    | 'ug'
    | 'uk-UA'
    | 'uk'
    | 'ur-PK'
    | 'ur'
    | 'uz-Cyrl-UZ'
    | 'uz-Latn-UZ'
    | 'uz-uz'
    | 'uz'
    | 've'
    | 'vi-VN'
    | 'vi'
    | 'vo'
    | 'wa'
    | 'wo-SN'
    | 'wo'
    | 'xh-ZA'
    | 'xh'
    | 'yi'
    | 'yo-NG'
    | 'yo'
    | 'za'
    | 'zh-CN'
    | 'zh-Hans'
    | 'zh-Hant'
    | 'zh-HK'
    | 'zh-MO'
    | 'zh-SG'
    | 'zh-TW'
    | 'zh'
    | 'zu-ZA'
    | 'zu'
  // We can't have all valid combinations of language-region-script listed here
  // as the list is too long and breaks the TypeScript compiler. So instead we
  // only add the most common ones with a general string pattern for the rest.
  // This way autocompletion still works and it is still possible to add custom
  // lang codes.
    | `${Lowercase<string>}-${string}`;

/**
 * @see {@link https://github.com/vercel/next.js/blob/e68639f83a4853c91f60aa6044bb4502a9365996/packages/next/src/lib/metadata/types/alternative-urls-types.ts#L429 Copy-pasted source}
 * @see {@link https://hreflang.org/what-is-a-valid-hreflang Reference}
 */
type SitemapLanguages<T> = {
  [s in HrefLang]?: T | undefined
};

/**
 * @see {@link https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/metadata/types/metadata-types.ts#L163C1-L166C2 Source}
 */
type SitemapRestriction = {
  content: string;
  relationship: 'allow' | 'deny';
};

/**
 * @see {@link https://github.com/vercel/next.js/blob/canary/packages/next/src/lib/metadata/types/metadata-types.ts#L168 Source}
 */
type SitemapVideo = {
  content_loc?: string | undefined;
  description: string;
  duration?: number | undefined;
  expiration_date?: Date | string | undefined;
  family_friendly?: 'no' | 'yes' | undefined;
  live?: 'no' | 'yes' | undefined;
  platform?: SitemapRestriction | undefined;
  player_loc?: string | undefined;
  publication_date?: Date | string | undefined;
  rating?: number | undefined;
  requires_subscription?: 'no' | 'yes' | undefined;
  restriction?: SitemapRestriction | undefined;
  tag?: string | undefined;
  thumbnail_loc: string;
  title: string;
  uploader?:
    | {
      content?: string | undefined;
      info?: string | undefined;
    }
    | undefined;
  view_count?: number | undefined;
};

type UnmatchedLang = 'x-default';
