/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GrowthsAndStatsRouteImport } from './routes/growths-and-stats'
import { Route as DamageRouteImport } from './routes/damage'
import { Route as IndexRouteImport } from './routes/index'

const GrowthsAndStatsRoute = GrowthsAndStatsRouteImport.update({
  id: '/growths-and-stats',
  path: '/growths-and-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageRoute = DamageRouteImport.update({
  id: '/damage',
  path: '/damage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/damage': typeof DamageRoute
  '/growths-and-stats': typeof GrowthsAndStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/damage': typeof DamageRoute
  '/growths-and-stats': typeof GrowthsAndStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/damage': typeof DamageRoute
  '/growths-and-stats': typeof GrowthsAndStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/damage' | '/growths-and-stats'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/damage' | '/growths-and-stats'
  id: '__root__' | '/' | '/damage' | '/growths-and-stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DamageRoute: typeof DamageRoute
  GrowthsAndStatsRoute: typeof GrowthsAndStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/growths-and-stats': {
      id: '/growths-and-stats'
      path: '/growths-and-stats'
      fullPath: '/growths-and-stats'
      preLoaderRoute: typeof GrowthsAndStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage': {
      id: '/damage'
      path: '/damage'
      fullPath: '/damage'
      preLoaderRoute: typeof DamageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DamageRoute: DamageRoute,
  GrowthsAndStatsRoute: GrowthsAndStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
