/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiScreenshotRouteImport } from './routes/api/screenshot'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRouteImport } from './routes/[.]well-known/appspecific/com[.]chrome[.]devtools[.]json'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotRoute = ApiScreenshotRouteImport.update({
  id: '/api/screenshot',
  path: '/api/screenshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRoute =
  DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRouteImport.update({
    id: '/.well-known/appspecific/com.chrome.devtools.json',
    path: '/.well-known/appspecific/com.chrome.devtools.json',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.well-known/appspecific/com.chrome.devtools.json': typeof DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/.well-known/appspecific/com.chrome.devtools.json': typeof DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/projects': typeof ProjectsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/health': typeof ApiHealthRoute
  '/api/screenshot': typeof ApiScreenshotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/.well-known/appspecific/com.chrome.devtools.json': typeof DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manifest.webmanifest'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/screenshot'
    | '/blog/$slug'
    | '/blog/'
    | '/.well-known/appspecific/com.chrome.devtools.json'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifest.webmanifest'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/screenshot'
    | '/blog/$slug'
    | '/blog'
    | '/.well-known/appspecific/com.chrome.devtools.json'
  id:
    | '__root__'
    | '/'
    | '/manifest.webmanifest'
    | '/projects'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/health'
    | '/api/screenshot'
    | '/blog/$slug'
    | '/blog/'
    | '/.well-known/appspecific/com.chrome.devtools.json'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  ProjectsRoute: typeof ProjectsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiScreenshotRoute: typeof ApiScreenshotRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRoute: typeof DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshot': {
      id: '/api/screenshot'
      path: '/api/screenshot'
      fullPath: '/api/screenshot'
      preLoaderRoute: typeof ApiScreenshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/appspecific/com.chrome.devtools.json': {
      id: '/.well-known/appspecific/com.chrome.devtools.json'
      path: '/.well-known/appspecific/com.chrome.devtools.json'
      fullPath: '/.well-known/appspecific/com.chrome.devtools.json'
      preLoaderRoute: typeof DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  ProjectsRoute: ProjectsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiScreenshotRoute: ApiScreenshotRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRoute:
    DotwellKnownAppspecificComDotchromeDotdevtoolsDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
