/**
 * Accordion components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/accordion}
 */

import { Accordion as AccordionPrimitive } from '@base-ui/react/accordion';
import { CaretDownIcon, CaretUpIcon } from '@phosphor-icons/react';
import { cn, tw } from '@/lib/utils';

/**
 *
 * @param root0
 * @param root0.className
 */
function Accordion({ className, ...props }: AccordionPrimitive.Root.Props) {
  return (
    <AccordionPrimitive.Root
      className={cn(tw`flex w-full flex-col`, className)}
      data-slot="accordion"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.children
 * @param root0.className
 */
function AccordionContent({
  children,
  className,
  ...props
}: AccordionPrimitive.Panel.Props) {
  return (
    <AccordionPrimitive.Panel
      className={tw`data-open:animate-accordion-down data-closed:animate-accordion-up text-sm overflow-hidden`}
      data-slot="accordion-content"
      {...props}
    >
      <div
        className={cn(
          'pt-0 pb-2.5 [&_a]:hover:text-foreground h-(--accordion-panel-height) data-ending-style:h-0 data-starting-style:h-0 [&_a]:underline [&_a]:underline-offset-3 [&_p:not(:last-child)]:mb-4',
          className,
        )}
      >
        {children}
      </div>
    </AccordionPrimitive.Panel>
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AccordionItem({ className, ...props }: AccordionPrimitive.Item.Props) {
  return (
    <AccordionPrimitive.Item
      className={cn('not-last:border-b', className)}
      data-slot="accordion-item"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.children
 * @param root0.className
 */
function AccordionTrigger({
  children,
  className,
  ...props
}: AccordionPrimitive.Trigger.Props) {
  return (
    <AccordionPrimitive.Header className="flex">
      <AccordionPrimitive.Trigger
        className={cn(
          tw`focus-visible:ring-ring/50 focus-visible:border-ring focus-visible:after:border-ring **:data-[slot=accordion-trigger-icon]:text-muted-foreground rounded-lg py-2.5 text-left text-sm font-medium hover:underline focus-visible:ring-[3px] **:data-[slot=accordion-trigger-icon]:ml-auto **:data-[slot=accordion-trigger-icon]:size-4 group/accordion-trigger relative flex flex-1 items-start justify-between border border-transparent transition-all outline-none disabled:pointer-events-none disabled:opacity-50`,
          className,
        )}
        data-slot="accordion-trigger"
        {...props}
      >
        {children}
        <CaretDownIcon className={tw`pointer-events-none shrink-0 group-aria-expanded/accordion-trigger:hidden`} data-slot="accordion-trigger-icon" />
        <CaretUpIcon className={tw`pointer-events-none hidden shrink-0 group-aria-expanded/accordion-trigger:inline`} data-slot="accordion-trigger-icon" />
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  );
}

export { Accordion, AccordionContent, AccordionItem, AccordionTrigger };
