/**
 * Alert components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/alert}
 */

import type { ComponentProps } from 'react';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn, tw } from '@/lib/utils';

const alertVariants = cva(tw`grid gap-0.5 rounded-lg border px-2.5 py-2 text-left text-sm has-data-[slot=alert-action]:relative has-data-[slot=alert-action]:pr-18 has-[>svg]:grid-cols-[auto_1fr] has-[>svg]:gap-x-2 *:[svg]:row-span-2 *:[svg]:translate-y-0.5 *:[svg]:text-current *:[svg:not([class*='size-'])]:size-4 w-full relative group/alert`, {
  defaultVariants: {
    variant: 'default',
  },
  variants: {
    variant: {
      default: tw`bg-card text-card-foreground`,
      destructive: tw`text-destructive bg-card *:data-[slot=alert-description]:text-destructive/90 *:[svg]:text-current`,
    },
  },
});

/**
 *
 * @param root0
 * @param root0.className
 * @param root0.variant
 */
function Alert({
  className,
  variant,
  ...props
}: ComponentProps<'div'> & VariantProps<typeof alertVariants>) {
  return (
    <div
      className={cn(alertVariants({ variant }), className)}
      data-slot="alert"
      role="alert"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AlertAction({ className, ...props }: ComponentProps<'div'>) {
  return (
    <div
      className={cn(tw`absolute top-2 right-2`, className)}
      data-slot="alert-action"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AlertDescription({
  className,
  ...props
}: ComponentProps<'div'>) {
  return (
    <div
      className={cn(
        tw`text-muted-foreground text-sm text-balance md:text-pretty [&_p:not(:last-child)]:mb-4 [&_a]:hover:text-foreground [&_a]:underline [&_a]:underline-offset-3`,
        className,
      )}
      data-slot="alert-description"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AlertTitle({ className, ...props }: ComponentProps<'div'>) {
  return (
    <div
      className={cn(
        tw`font-medium group-has-[>svg]/alert:col-start-2 [&_a]:hover:text-foreground [&_a]:underline [&_a]:underline-offset-3`,
        className,
      )}
      data-slot="alert-title"
      {...props}
    />
  );
}

export { Alert, AlertAction, AlertDescription, AlertTitle };
