/**
 * Avatar components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/avatar}
 */

import { Avatar as AvatarPrimitive } from '@base-ui/react/avatar';
import { cn, tw } from '@/lib/utils';

/**
 *
 * @param root0
 * @param root0.className
 * @param root0.size
 */
function Avatar({
  className,
  size = 'default',
  ...props
}: {
  size?: 'default' | 'lg' | 'sm';
} & AvatarPrimitive.Root.Props) {
  return (
    <AvatarPrimitive.Root
      className={cn(
        tw`size-8 rounded-full after:rounded-full data-[size=lg]:size-10 data-[size=sm]:size-6 after:border-border group/avatar relative flex shrink-0 select-none after:absolute after:inset-0 after:border after:mix-blend-darken dark:after:mix-blend-lighten`,
        className,
      )}
      data-size={size}
      data-slot="avatar"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AvatarBadge({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span
      className={cn(
        tw`bg-primary text-primary-foreground ring-background absolute right-0 bottom-0 z-10 inline-flex items-center justify-center rounded-full bg-blend-color ring-2 select-none`,
        tw`group-data-[size=sm]/avatar:size-2 group-data-[size=sm]/avatar:[&>svg]:hidden`,
        tw`group-data-[size=default]/avatar:size-2.5 group-data-[size=default]/avatar:[&>svg]:size-2`,
        tw`group-data-[size=lg]/avatar:size-3 group-data-[size=lg]/avatar:[&>svg]:size-2`,
        className,
      )}
      data-slot="avatar-badge"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AvatarFallback({
  className,
  ...props
}: AvatarPrimitive.Fallback.Props) {
  return (
    <AvatarPrimitive.Fallback
      className={cn(
        tw`bg-muted text-muted-foreground rounded-full flex size-full items-center justify-center text-sm group-data-[size=sm]/avatar:text-xs`,
        className,
      )}
      data-slot="avatar-fallback"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AvatarGroup({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(
        tw`*:data-[slot=avatar]:ring-background group/avatar-group flex -space-x-2 *:data-[slot=avatar]:ring-2`,
        className,
      )}
      data-slot="avatar-group"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AvatarGroupCount({
  className,
  ...props
}: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(tw`bg-muted text-muted-foreground size-8 rounded-full text-sm group-has-data-[size=lg]/avatar-group:size-10 group-has-data-[size=sm]/avatar-group:size-6 [&>svg]:size-4 group-has-data-[size=lg]/avatar-group:[&>svg]:size-5 group-has-data-[size=sm]/avatar-group:[&>svg]:size-3 ring-background relative flex shrink-0 items-center justify-center ring-2`, className)}
      data-slot="avatar-group-count"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function AvatarImage({ className, ...props }: AvatarPrimitive.Image.Props) {
  return (
    <AvatarPrimitive.Image
      className={cn(
        tw`rounded-full aspect-square size-full object-cover`,
        className,
      )}
      data-slot="avatar-image"
      {...props}
    />
  );
}

export {
  Avatar,
  AvatarBadge,
  AvatarFallback,
  AvatarGroup,
  AvatarGroupCount,
  AvatarImage,
};
