/**
 * Card components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/card}
 */

import * as React from 'react';

import { cn, tw } from '@/lib/utils';

/**
 *
 * @param root0
 * @param root0.className
 * @param root0.size
 */
function Card({
  className,
  size = 'default',
  ...props
}: { size?: 'default' | 'sm' } & React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(tw`ring-foreground/10 bg-card text-card-foreground gap-4 overflow-hidden rounded-xl py-4 text-sm ring-1 has-data-[slot=card-footer]:pb-0 has-[>img:first-child]:pt-0 data-[size=sm]:gap-3 data-[size=sm]:py-3 data-[size=sm]:has-data-[slot=card-footer]:pb-0 *:[img:first-child]:rounded-t-xl *:[img:last-child]:rounded-b-xl group/card flex flex-col`, className)}
      data-size={size}
      data-slot="card"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function CardAction({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(
        tw`col-start-2 row-span-2 row-start-1 self-start justify-self-end`,
        className,
      )}
      data-slot="card-action"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function CardContent({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(tw`px-4 group-data-[size=sm]/card:px-3`, className)}
      data-slot="card-content"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function CardDescription({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(tw`text-muted-foreground text-sm`, className)}
      data-slot="card-description"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function CardFooter({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(tw`bg-muted/50 rounded-b-xl border-t p-4 group-data-[size=sm]/card:p-3 flex items-center`, className)}
      data-slot="card-footer"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function CardHeader({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(
        tw`gap-1 rounded-t-xl px-4 group-data-[size=sm]/card:px-3 [.border-b]:pb-4 group-data-[size=sm]/card:[.border-b]:pb-3 group/card-header @container/card-header grid auto-rows-min items-start has-data-[slot=card-action]:grid-cols-[1fr_auto] has-data-[slot=card-description]:grid-rows-[auto_auto]`,
        className,
      )}
      data-slot="card-header"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function CardTitle({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(tw`text-base leading-snug font-medium group-data-[size=sm]/card:text-sm`, className)}
      data-slot="card-title"
      {...props}
    />
  );
}

export {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
};
