/**
 * Dropdown Menu components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/dropdown-menu}
 */

import { Menu as MenuPrimitive } from '@base-ui/react/menu';
import { CaretRightIcon, CheckIcon } from '@phosphor-icons/react';
import { cn, tw } from '@/lib/utils';

/**
 * Groups all parts of the menu. Doesn’t render its own HTML element.
 * @param props Component props
 * @returns Renders a react component
 */
function DropdownMenu({ ...props }: MenuPrimitive.Root.Props) {
  return <MenuPrimitive.Root data-slot="dropdown-menu" {...props} />;
}

/**
 * Use `DropdownMenuCheckboxItem` for toggles.
 * @param props Component props
 * @param props.checked Whether the checkbox item is checked
 * @param props.children Content The content
 * @param props.className Customize and override default classes if needed
 * @returns Renders a react component
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuContent>
 *     <DropdownMenuGroup>
 *       <DropdownMenuLabel>...</DropdownMenuLabel>
 *       <DropdownMenuCheckboxItem ... />
 *       <DropdownMenuCheckboxItem ... />
 *       <DropdownMenuCheckboxItem ... />
 *     </DropdownMenuGroup>
 *   </DropdownMenuContent>
 * </DropdownMenu>
 * ```
 */
function DropdownMenuCheckboxItem({
  checked,
  children,
  className,
  ...props
}: MenuPrimitive.CheckboxItem.Props) {
  return (
    <MenuPrimitive.CheckboxItem
      checked={checked}
      className={cn(
        tw`focus:bg-accent focus:text-accent-foreground focus:**:text-accent-foreground gap-1.5 rounded-md py-1 pr-8 pl-1.5 text-sm [&_svg:not([class*='size-'])]:size-4 relative flex cursor-default items-center outline-hidden select-none data-disabled:pointer-events-none data-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0`,
        className,
      )}
      data-slot="dropdown-menu-checkbox-item"
      {...props}
    >
      <span
        className={tw`absolute right-2 flex items-center justify-center pointer-events-none`}
        data-slot="dropdown-menu-checkbox-item-indicator"
      >
        <MenuPrimitive.CheckboxItemIndicator>
          <CheckIcon />
        </MenuPrimitive.CheckboxItemIndicator>
      </span>
      {children}
    </MenuPrimitive.CheckboxItem>
  );
}

/**
 * A container for the menu items. Renders a `<div>` element by default
 * @param props Component props
 * @param props.align How to align the popup relative to the specified side
 * @param props.alignOffset Additional offset along the alignment axis in pixels. Also accepts a function that returns the offset to read the dimensions of the anchor and positioner elements, along with its side and alignment.
 * @param props.className Customize and override default classes if needed
 * @param props.side Which side of the anchor to align the popup against when opening
 * @param props.sideOffset Distance of the popup relative to the anchor
 * @returns Renders a react component
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuTrigger>...</DropdownMenuTrigger>
 *   <DropdownMenuContent>...</DropdownMenuContent>
 * </DropdownMenu>
 * ```
 */
function DropdownMenuContent({
  align = 'start',
  alignOffset = 0,
  className,
  side = 'bottom',
  sideOffset = 4,
  ...props
}: MenuPrimitive.Popup.Props
  & Pick<
    MenuPrimitive.Positioner.Props,
    'align' | 'alignOffset' | 'side' | 'sideOffset'
  >) {
  return (
    <MenuPrimitive.Portal>
      <MenuPrimitive.Positioner
        align={align}
        alignOffset={alignOffset}
        className={tw`isolate z-50 outline-none`}
        side={side}
        sideOffset={sideOffset}
      >
        <MenuPrimitive.Popup
          className={cn(tw`data-open:animate-in data-closed:animate-out data-closed:fade-out-0 data-open:fade-in-0 data-closed:zoom-out-95 data-open:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 ring-foreground/10 bg-popover text-popover-foreground min-w-32 rounded-lg p-1 shadow-md ring-1 duration-100 z-50 max-h-(--available-height) w-(--anchor-width) origin-(--transform-origin) overflow-x-hidden overflow-y-auto outline-none data-closed:overflow-hidden`, className)}
          data-slot="dropdown-menu-content"
          {...props}
        />
      </MenuPrimitive.Positioner>
    </MenuPrimitive.Portal>
  );
}

/**
 *
 * @param props Component props
 * @returns Renders a react element
 */
function DropdownMenuGroup({ ...props }: MenuPrimitive.Group.Props) {
  return <MenuPrimitive.Group data-slot="dropdown-menu-group" {...props} />;
}

/**
 *
 * @param props Component props
 * @param props.className Customize and override default classes if needed
 * @param props.inset Whether to add insets to the content
 * @param props.variant Use variant="destructive" for irreversible actions.
 * @returns Renders a react element
 */
function DropdownMenuItem({
  className,
  inset,
  variant = 'default',
  ...props
}: {
  inset?: boolean;
  variant?: 'default' | 'destructive';
} & MenuPrimitive.Item.Props) {
  return (
    <MenuPrimitive.Item
      className={cn(
        tw`focus:bg-accent focus:text-accent-foreground data-[variant=destructive]:text-destructive data-[variant=destructive]:focus:bg-destructive/10 dark:data-[variant=destructive]:focus:bg-destructive/20 data-[variant=destructive]:focus:text-destructive data-[variant=destructive]:*:[svg]:text-destructive not-data-[variant=destructive]:focus:**:text-accent-foreground gap-1.5 rounded-md px-1.5 py-1 text-sm [&_svg:not([class*='size-'])]:size-4 group/dropdown-menu-item relative flex cursor-default items-center outline-hidden select-none data-disabled:pointer-events-none data-disabled:opacity-50 data-inset:pl-8 [&_svg]:pointer-events-none [&_svg]:shrink-0`,
        className,
      )}
      data-inset={inset}
      data-slot="dropdown-menu-item"
      data-variant={variant}
      {...props}
    />
  );
}

/**
 * An accessible label that is automatically associated with its parent group
 * @param props Component props
 * @param props.className Customize and override default classes if needed
 * @param props.inset Whether to add insets to the content
 * @returns Renders a react element
 */
function DropdownMenuLabel({
  className,
  inset,
  ...props
}: {
  inset?: boolean;
} & MenuPrimitive.GroupLabel.Props) {
  return (
    <MenuPrimitive.GroupLabel
      className={cn(tw`text-muted-foreground px-1.5 py-1 text-xs font-medium data-inset:pl-8`, className)}
      data-inset={inset}
      data-slot="dropdown-menu-label"
      {...props}
    />
  );
}

/**
 *
 * @param props Component props
 * @returns Renders a react element
 */
function DropdownMenuPortal({ ...props }: MenuPrimitive.Portal.Props) {
  return <MenuPrimitive.Portal data-slot="dropdown-menu-portal" {...props} />;
}

/**
 * Use `DropdownMenuRadioGroup` for exclusive choices.
 * @param props Component props
 * @returns Renders a react component
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuContent>
 *     <DropdownMenuGroup>
 *       <DropdownMenuLabel>...</DropdownMenuLabel>
 *       <DropdownMenuRadioGroup value={position} onValueChange={setPosition}>
 *         <DropdownMenuRadioItem value="top">Top</DropdownMenuRadioItem>
 *         <DropdownMenuRadioItem value="bottom">Bottom</DropdownMenuRadioItem>
 *         <DropdownMenuRadioItem value="right">Right</DropdownMenuRadioItem>
 *       </DropdownMenuRadioGroup>
 *     </DropdownMenuGroup>
 *   </DropdownMenuContent>
 * </DropdownMenu>
 * ```
 */
function DropdownMenuRadioGroup({ ...props }: MenuPrimitive.RadioGroup.Props) {
  return (
    <MenuPrimitive.RadioGroup
      data-slot="dropdown-menu-radio-group"
      {...props}
    />
  );
}

/**
 * Use `DropdownMenuRadioGroup` for exclusive choices.
 * @param props Component props
 * @param props.children Content
 * @param props.className Customize and override default classes if needed
 * @returns Renders a react component
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuContent>
 *     <DropdownMenuGroup>
 *       <DropdownMenuLabel>...</DropdownMenuLabel>
 *       <DropdownMenuRadioGroup value={position} onValueChange={setPosition}>
 *         <DropdownMenuRadioItem value="top">Top</DropdownMenuRadioItem>
 *         <DropdownMenuRadioItem value="bottom">Bottom</DropdownMenuRadioItem>
 *         <DropdownMenuRadioItem value="right">Right</DropdownMenuRadioItem>
 *       </DropdownMenuRadioGroup>
 *     </DropdownMenuGroup>
 *   </DropdownMenuContent>
 * </DropdownMenu>
 * ```
 */
function DropdownMenuRadioItem({
  children,
  className,
  ...props
}: MenuPrimitive.RadioItem.Props) {
  return (
    <MenuPrimitive.RadioItem
      className={cn(
        tw`focus:bg-accent focus:text-accent-foreground focus:**:text-accent-foreground gap-1.5 rounded-md py-1 pr-8 pl-1.5 text-sm [&_svg:not([class*='size-'])]:size-4 relative flex cursor-default items-center outline-hidden select-none data-disabled:pointer-events-none data-disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0`,
        className,
      )}
      data-slot="dropdown-menu-radio-item"
      {...props}
    >
      <span
        className={tw`absolute right-2 flex items-center justify-center pointer-events-none`}
        data-slot="dropdown-menu-radio-item-indicator"
      >
        <MenuPrimitive.RadioItemIndicator>
          <CheckIcon />
        </MenuPrimitive.RadioItemIndicator>
      </span>
      {children}
    </MenuPrimitive.RadioItem>
  );
}

/**
 *
 * @param props Component props
 * @param props.className Customize and override default classes if needed
 * @returns Renders a react element
 */
function DropdownMenuSeparator({
  className,
  ...props
}: MenuPrimitive.Separator.Props) {
  return (
    <MenuPrimitive.Separator
      className={cn(tw`bg-border -mx-1 my-1 h-px`, className)}
      data-slot="dropdown-menu-separator"
      {...props}
    />
  );
}

/**
 * Add `DropdownMenuShortcut` to show keyboard hints.
 * @param props Component props
 * @param props.className Customize and override default classes if needed
 * @returns Renders a react element
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuTrigger render={<Button variant="outline">Open</Button>} />
 *   <DropdownMenuContent>
 *     <DropdownMenuGroup>
 *       <DropdownMenuLabel>My Account</DropdownMenuLabel>
 *       <DropdownMenuItem>
 *         Profile
 *         <DropdownMenuShortcut>⇧⌘P</DropdownMenuShortcut>
 *       </DropdownMenuItem>
 *     </DropdownMenuGroup>
 *   </DropdownMenuContent>
 * </DropdownMenu>
 * ```
 */
function DropdownMenuShortcut({
  className,
  ...props
}: React.ComponentProps<'span'>) {
  return (
    <span
      className={cn(tw`text-muted-foreground group-focus/dropdown-menu-item:text-accent-foreground ml-auto text-xs tracking-widest`, className)}
      data-slot="dropdown-menu-shortcut"
      {...props}
    />
  );
}

/**
 * Use `DropdownMenuSub` to nest secondary actions.
 *
 * IMPORTANT: `DropdownMenuSub` can be nested more than once
 * @param props Component props
 * @returns Renders a react element
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuTrigger render={<Button variant="outline">Open</Button>} />
 *   <DropdownMenuContent>
 *     <DropdownMenuGroup>
 *       <DropdownMenuItem>Team</DropdownMenuItem>
 *       <DropdownMenuSub>
 *         <DropdownMenuSubTrigger>Invite users</DropdownMenuSubTrigger>
 *         <DropdownMenuPortal>
 *           <DropdownMenuSubContent>
 *             <DropdownMenuItem>Email</DropdownMenuItem>
 *             <DropdownMenuItem>Message</DropdownMenuItem>
 *           </DropdownMenuSubContent>
 *         </DropdownMenuPortal>
 *       </DropdownMenuSub>
 *     <DropdownMenuGroup>
 *   <DropdownMenuContent>
 * <DropdownMenu>
 * ```
 */
function DropdownMenuSub({ ...props }: MenuPrimitive.SubmenuRoot.Props) {
  return <MenuPrimitive.SubmenuRoot data-slot="dropdown-menu-sub" {...props} />;
}

/**
 * Use `DropdownMenuSub` to nest secondary actions.
 *
 * IMPORTANT: `DropdownMenuSub` can be nested more than once
 * @param props Component props
 * @param props.align How to align the popup relative to the specified side
 * @param props.alignOffset Additional offset along the alignment axis in pixels. Also accepts a function that returns the offset to read the dimensions of the anchor and positioner elements, along with its side and alignment.
 * @param props.className Customize and override default classes if needed
 * @param props.side Which side of the anchor to align the popup against when opening
 * @param props.sideOffset Distance of the popup relative to the anchor
 * @returns Renders a react element
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuTrigger render={<Button variant="outline">Open</Button>} />
 *   <DropdownMenuContent>
 *     <DropdownMenuGroup>
 *       <DropdownMenuItem>Team</DropdownMenuItem>
 *       <DropdownMenuSub>
 *         <DropdownMenuSubTrigger>Invite users</DropdownMenuSubTrigger>
 *         <DropdownMenuPortal>
 *           <DropdownMenuSubContent>
 *             <DropdownMenuItem>Email</DropdownMenuItem>
 *             <DropdownMenuItem>Message</DropdownMenuItem>
 *           </DropdownMenuSubContent>
 *         </DropdownMenuPortal>
 *       </DropdownMenuSub>
 *     <DropdownMenuGroup>
 *   <DropdownMenuContent>
 * <DropdownMenu>
 * ```
 */
function DropdownMenuSubContent({
  align = 'start',
  alignOffset = -3,
  className,
  side = 'right',
  sideOffset = 0,
  ...props
}: React.ComponentProps<typeof DropdownMenuContent>) {
  return (
    <DropdownMenuContent
      align={align}
      alignOffset={alignOffset}
      className={cn(tw`data-open:animate-in data-closed:animate-out data-closed:fade-out-0 data-open:fade-in-0 data-closed:zoom-out-95 data-open:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 ring-foreground/10 bg-popover text-popover-foreground min-w-[96px] rounded-md p-1 shadow-lg ring-1 duration-100 w-auto`, className)}
      data-slot="dropdown-menu-sub-content"
      side={side}
      sideOffset={sideOffset}
      {...props}
    />
  );
}

/**
 * Use `DropdownMenuSub` to nest secondary actions.
 *
 * IMPORTANT: `DropdownMenuSub` can be nested more than once
 * @param props Component props
 * @param props.children Content
 * @param props.className Customize and override default classes if needed
 * @param props.inset Whether to add insets to the content
 * @returns Renders a react element
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuTrigger render={<Button variant="outline">Open</Button>} />
 *   <DropdownMenuContent>
 *     <DropdownMenuGroup>
 *       <DropdownMenuItem>Team</DropdownMenuItem>
 *       <DropdownMenuSub>
 *         <DropdownMenuSubTrigger>Invite users</DropdownMenuSubTrigger>
 *         <DropdownMenuPortal>
 *           <DropdownMenuSubContent>
 *             <DropdownMenuItem>Email</DropdownMenuItem>
 *             <DropdownMenuItem>Message</DropdownMenuItem>
 *           </DropdownMenuSubContent>
 *         </DropdownMenuPortal>
 *       </DropdownMenuSub>
 *     <DropdownMenuGroup>
 *   <DropdownMenuContent>
 * <DropdownMenu>
 * ```
 */
function DropdownMenuSubTrigger({
  children,
  className,
  inset,
  ...props
}: {
  inset?: boolean;
} & MenuPrimitive.SubmenuTrigger.Props) {
  return (
    <MenuPrimitive.SubmenuTrigger
      className={cn(
        tw`focus:bg-accent focus:text-accent-foreground data-open:bg-accent data-open:text-accent-foreground not-data-[variant=destructive]:focus:**:text-accent-foreground gap-1.5 rounded-md px-1.5 py-1 text-sm [&_svg:not([class*='size-'])]:size-4 flex cursor-default items-center outline-hidden select-none data-inset:pl-8 [&_svg]:pointer-events-none [&_svg]:shrink-0`,
        className,
      )}
      data-inset={inset}
      data-slot="dropdown-menu-sub-trigger"
      {...props}
    >
      {children}
      <CaretRightIcon className="ml-auto" />
    </MenuPrimitive.SubmenuTrigger>
  );
}

/**
 *
 * @param props Component props
 * @returns Renders a react component
 * @example
 * ```tsx
 * <DropdownMenu>
 *   <DropdownMenuTrigger>...</DropdownMenuTrigger>
 *   <DropdownMenuContent>...</DropdownMenuContent>
 * </DropdownMenu>
 * ```
 */
function DropdownMenuTrigger({ ...props }: MenuPrimitive.Trigger.Props) {
  return <MenuPrimitive.Trigger data-slot="dropdown-menu-trigger" {...props} />;
}

export {
  DropdownMenu,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
};
