/**
 * Field components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/field}
 */

import { cva, type VariantProps } from 'class-variance-authority';
import { useMemo } from 'react';

import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { cn, tw } from '@/lib/utils';

/**
 *
 * @param root0
 * @param root0.className
 */
function FieldGroup({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(
        tw`gap-5 data-[slot=checkbox-group]:gap-3 *:data-[slot=field-group]:gap-4 group/field-group @container/field-group flex w-full flex-col`,
        className,
      )}
      data-slot="field-group"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 * @param root0.variant
 */
function FieldLegend({
  className,
  variant = 'legend',
  ...props
}: { variant?: 'label' | 'legend' } & React.ComponentProps<'legend'>) {
  return (
    <legend
      className={cn(tw`mb-1.5 font-medium data-[variant=label]:text-sm data-[variant=legend]:text-base`, className)}
      data-slot="field-legend"
      data-variant={variant}
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function FieldSet({ className, ...props }: React.ComponentProps<'fieldset'>) {
  return (
    <fieldset
      className={cn(tw`gap-4 has-[>[data-slot=checkbox-group]]:gap-3 has-[>[data-slot=radio-group]]:gap-3 flex flex-col`, className)}
      data-slot="field-set"
      {...props}
    />
  );
}

const fieldVariants = cva(tw`data-[invalid=true]:text-destructive gap-2 group/field flex w-full`, {
  defaultVariants: {
    orientation: 'vertical',
  },
  variants: {
    orientation: {
      horizontal:
        tw`flex-row items-center *:data-[slot=field-label]:flex-auto has-[>[data-slot=field-content]]:items-start has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px`,
      responsive:
        tw`flex-col *:w-full [&>.sr-only]:w-auto @md/field-group:flex-row @md/field-group:items-center @md/field-group:*:w-auto @md/field-group:*:data-[slot=field-label]:flex-auto @md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px`,
      vertical:
        tw`flex-col *:w-full [&>.sr-only]:w-auto`,
    },
  },
});

/**
 *
 * @param root0
 * @param root0.className
 * @param root0.orientation
 */
function Field({
  className,
  orientation = 'vertical',
  ...props
}: React.ComponentProps<'div'> & VariantProps<typeof fieldVariants>) {
  return (
    <div
      className={cn(fieldVariants({ orientation }), className)}
      data-orientation={orientation}
      data-slot="field"
      role="group"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function FieldContent({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(
        tw`gap-0.5 group/field-content flex flex-1 flex-col leading-snug`,
        className,
      )}
      data-slot="field-content"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function FieldDescription({ className, ...props }: React.ComponentProps<'p'>) {
  return (
    <p
      className={cn(
        tw`text-muted-foreground text-left text-sm [[data-variant=legend]+&]:-mt-1.5 leading-normal font-normal group-has-data-[orientation=horizontal]/field:text-balance`,
        tw`last:mt-0 nth-last-2:-mt-1`,
        tw`[&>a:hover]:text-primary [&>a]:underline [&>a]:underline-offset-4`,
        className,
      )}
      data-slot="field-description"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.children
 * @param root0.className
 * @param root0.errors
 */
function FieldError({
  children,
  className,
  errors,
  ...props
}: {
  errors?: Array<{ message?: string } | undefined>;
} & React.ComponentProps<'div'>) {
  const content = useMemo(() => {
    if (children) {
      return children;
    }

    if (!errors?.length) {
      return null;
    }

    const uniqueErrors = [
      ...new Map(errors.map((error) => [error?.message, error])).values(),
    ];

    if (uniqueErrors?.length == 1) {
      return uniqueErrors[0]?.message;
    }

    return (
      <ul className={tw`ml-4 flex list-disc flex-col gap-1`}>
        {uniqueErrors.map(
          (error, index) =>
            error?.message && <li key={index}>{error.message}</li>,
        )}
      </ul>
    );
  }, [children, errors]);

  if (!content) {
    return null;
  }

  return (
    <div
      className={cn(tw`text-destructive text-sm font-normal`, className)}
      data-slot="field-error"
      role="alert"
      {...props}
    >
      {content}
    </div>
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function FieldLabel({
  className,
  ...props
}: React.ComponentProps<typeof Label>) {
  return (
    <Label
      className={cn(
        tw`has-data-checked:bg-primary/5 has-data-checked:border-primary dark:has-data-checked:bg-primary/10 gap-2 group-data-[disabled=true]/field:opacity-50 has-[>[data-slot=field]]:rounded-lg has-[>[data-slot=field]]:border *:data-[slot=field]:p-2.5 group/field-label peer/field-label flex w-fit leading-snug`,
        tw`has-[>[data-slot=field]]:w-full has-[>[data-slot=field]]:flex-col`,
        className,
      )}
      data-slot="field-label"
      {...props}
    />
  );
}

/**
 *
 * @param root0
 * @param root0.children
 * @param root0.className
 */
function FieldSeparator({
  children,
  className,
  ...props
}: {
  children?: React.ReactNode;
} & React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(tw`-my-2 h-5 text-sm group-data-[variant=outline]/field-group:-mb-2 relative`, className)}
      data-content={!!children}
      data-slot="field-separator"
      {...props}
    >
      <Separator className={tw`absolute inset-0 top-1/2`} />
      {children && (
        <span
          className={tw`text-muted-foreground px-2 bg-background relative mx-auto block w-fit`}
          data-slot="field-separator-content"
        >
          {children}
        </span>
      )}
    </div>
  );
}

/**
 *
 * @param root0
 * @param root0.className
 */
function FieldTitle({ className, ...props }: React.ComponentProps<'div'>) {
  return (
    <div
      className={cn(
        tw`gap-2 text-sm font-medium group-data-[disabled=true]/field:opacity-50 flex w-fit items-center leading-snug`,
        className,
      )}
      data-slot="field-label"
      {...props}
    />
  );
}

export {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldTitle,
};
