/**
 * Input components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/input}
 */

import { Input as InputPrimitive } from '@base-ui/react/input';
import * as React from 'react';

import { cn, tw } from '@/lib/utils';

/**
 *
 * @param root0
 * @param root0.className
 * @param root0.type
 */
function Input({ className, type, ...props }: React.ComponentProps<'input'>) {
  return (
    <InputPrimitive
      className={cn(
        tw`dark:bg-input/30 border-input focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:aria-invalid:border-destructive/50 disabled:bg-input/50 dark:disabled:bg-input/80 h-8 rounded-lg border bg-transparent px-2.5 py-1 text-base transition-colors file:h-6 file:text-sm file:font-medium focus-visible:ring-[3px] aria-invalid:ring-[3px] md:text-sm file:text-foreground placeholder:text-muted-foreground w-full min-w-0 outline-none file:inline-flex file:border-0 file:bg-transparent disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50`,
        className,
      )}
      data-slot="input"
      type={type}
      {...props}
    />
  );
}

export { Input };
