/**
 * Separator components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/separator}
 */

import { Separator as SeparatorPrimitive } from '@base-ui/react/separator';

import { cn, tw } from '@/lib/utils';

/**
 *
 * @param root0
 * @param root0.className
 * @param root0.orientation
 */
function Separator({
  className,
  orientation = 'horizontal',
  ...props
}: SeparatorPrimitive.Props) {
  return (
    <SeparatorPrimitive
      className={cn(
        tw`bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:w-px data-[orientation=vertical]:self-stretch`,
        className,
      )}
      data-slot="separator"
      orientation={orientation}
      {...props}
    />
  );
}

export { Separator };
