/**
 * Sonner components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/sonner}
 *
 * Modified `useTheme` to use our custom `useTheme` rather than `next-themes`
 */

import { CheckCircleIcon, InfoIcon, SpinnerIcon, WarningIcon, XCircleIcon } from '@phosphor-icons/react';
import { Toaster as Sonner, type ToasterProps } from 'sonner';
import { useTheme } from '@/hooks/use-theme';
import { tw } from '@/lib/utils';

/**
 *
 * @param root0
 */
export function Toaster({ ...props }: Omit<ToasterProps, 'className' | 'icons' | 'style' | 'theme' | 'toastOptions'>) {
  const theme = useTheme();

  return (
    <Sonner
      className={tw`toaster group`}
      icons={{
        error: (
          <XCircleIcon className={tw`size-4`} />
        ),
        info: (
          <InfoIcon className={tw`size-4`} />
        ),
        loading: (
          <SpinnerIcon className={tw`size-4 animate-spin`} />
        ),
        success: (
          <CheckCircleIcon className={tw`size-4`} />
        ),
        warning: (
          <WarningIcon className={tw`size-4`} />
        ),
      }}
      style={
        {
          '--border-radius': 'var(--radius)',
          '--normal-bg': 'var(--popover)',
          '--normal-border': 'var(--border)',
          '--normal-text': 'var(--popover-foreground)',
        } as React.CSSProperties
      }
      theme={theme}
      toastOptions={{
        classNames: {
          toast: tw`cn-toast`,
        },
      }}
      {...props}
    />
  );
};
