/**
 * Textarea components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/textarea}
 */

import type { ComponentProps } from 'react';
import { cn, tw } from '@/lib/utils';

/**
 *
 * @param root0
 * @param root0.className
 */
function Textarea({ className, ...props }: ComponentProps<'textarea'>) {
  return (
    <textarea
      className={cn(
        tw`border-input dark:bg-input/30 focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:aria-invalid:border-destructive/50 disabled:bg-input/50 dark:disabled:bg-input/80 rounded-lg border bg-transparent px-2.5 py-2 text-base transition-colors focus-visible:ring-[3px] aria-invalid:ring-[3px] md:text-sm placeholder:text-muted-foreground flex field-sizing-content min-h-16 w-full outline-none disabled:cursor-not-allowed disabled:opacity-50`,
        className,
      )}
      data-slot="textarea"
      {...props}
    />
  );
}

export { Textarea };
