/**
 * Toggle components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/toggle}
 */

import { Toggle as TogglePrimitive } from '@base-ui/react/toggle';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn, tw } from '@/lib/utils';

const toggleVariants = cva(
  tw`hover:text-foreground aria-pressed:bg-muted focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive data-[state=on]:bg-muted gap-1 rounded-lg text-sm font-medium transition-all [&_svg:not([class*='size-'])]:size-4 group/toggle hover:bg-muted inline-flex items-center justify-center whitespace-nowrap outline-none focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0`,
  {
    defaultVariants: {
      size: 'default',
      variant: 'default',
    },
    variants: {
      size: {
        default: tw`h-8 min-w-8 px-2`,
        lg: tw`h-9 min-w-9 px-2.5`,
        sm: tw`h-7 min-w-7 rounded-[min(var(--radius-md),12px)] px-1.5 text-[0.8rem]`,
      },
      variant: {
        default: tw`bg-transparent`,
        outline: tw`border-input hover:bg-muted border bg-transparent`,
      },
    },
  },
);

/**
 *
 * @param root0
 * @param root0.className
 * @param root0.size
 * @param root0.variant
 */
function Toggle({
  className,
  size = 'default',
  variant = 'default',
  ...props
}: TogglePrimitive.Props & VariantProps<typeof toggleVariants>) {
  return (
    <TogglePrimitive
      className={cn(toggleVariants({ className, size, variant }))}
      data-slot="toggle"
      {...props}
    />
  );
}

export { Toggle, toggleVariants };
