/**
 * Toggle Group components generated by shadcn CLI
 * @see {@link https://ui.shadcn.com/docs/components/radix/toggle-group}
 */

import { Toggle as TogglePrimitive } from '@base-ui/react/toggle';
import { ToggleGroup as ToggleGroupPrimitive } from '@base-ui/react/toggle-group';
import { type VariantProps } from 'class-variance-authority';
import { createContext, type CSSProperties, use } from 'react';
import { toggleVariants } from '@/components/ui/toggle';
import { cn, tw } from '@/lib/utils';

const ToggleGroupContext = createContext<
  {
    orientation?: 'horizontal' | 'vertical';
    spacing?: number;
  } & VariantProps<typeof toggleVariants>
>({
  orientation: 'horizontal',
  size: 'default',
  spacing: 0,
  variant: 'default',
});

/**
 *
 * @param root0
 * @param root0.children
 * @param root0.className
 * @param root0.orientation
 * @param root0.size
 * @param root0.spacing
 * @param root0.variant
 */
function ToggleGroup({
  children,
  className,
  orientation = 'horizontal',
  size,
  spacing = 0,
  variant,
  ...props
}: {
  orientation?: 'horizontal' | 'vertical';
  spacing?: number;
}
& ToggleGroupPrimitive.Props & VariantProps<typeof toggleVariants>) {
  return (
    <ToggleGroupPrimitive
      className={cn(
        tw`rounded-lg data-[size=sm]:rounded-[min(var(--radius-md),10px)] group/toggle-group flex w-fit flex-row items-center gap-[--spacing(var(--gap))] data-[orientation=vertical]:flex-col data-[orientation=vertical]:items-stretch`,
        className,
      )}
      data-orientation={orientation}
      data-size={size}
      data-slot="toggle-group"
      data-spacing={spacing}
      data-variant={variant}
      style={{ '--gap': spacing } as CSSProperties}
      {...props}
    >
      <ToggleGroupContext
        value={{ orientation, size, spacing, variant }}
      >
        {children}
      </ToggleGroupContext>
    </ToggleGroupPrimitive>
  );
}

/**
 *
 * @param root0
 * @param root0.children
 * @param root0.className
 * @param root0.size
 * @param root0.variant
 */
function ToggleGroupItem({
  children,
  className,
  size = 'default',
  variant = 'default',
  ...props
}: TogglePrimitive.Props & VariantProps<typeof toggleVariants>) {
  const context = use(ToggleGroupContext);

  return (
    <TogglePrimitive
      className={cn(
        tw`group-data-[spacing=0]/toggle-group:rounded-none group-data-[spacing=0]/toggle-group:px-2 group-data-horizontal/toggle-group:data-[spacing=0]:first:rounded-l-lg group-data-vertical/toggle-group:data-[spacing=0]:first:rounded-t-lg group-data-horizontal/toggle-group:data-[spacing=0]:last:rounded-r-lg group-data-vertical/toggle-group:data-[spacing=0]:last:rounded-b-lg shrink-0 focus:z-10 focus-visible:z-10 group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:border-l-0 group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:border-t-0 group-data-horizontal/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-l group-data-vertical/toggle-group:data-[spacing=0]:data-[variant=outline]:first:border-t`,
        toggleVariants({
          size: context.size || size,
          variant: context.variant || variant,
        }),
        className,
      )}
      data-size={context.size || size}
      data-slot="toggle-group-item"
      data-spacing={context.spacing}
      data-variant={context.variant || variant}
      {...props}
    >
      {children}
    </TogglePrimitive>
  );
}

export { ToggleGroup, ToggleGroupItem };
