name: Deploy @apps/public-tanstack-start to Cloudflare

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Create .env file
        working-directory: apps/public-tanstack-start
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env
      
      - name: Build
        working-directory: apps/public-tanstack-start
        env:
          CLOUDFLARE: true
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          CLOUDFLARE_ENV: ${{ github.ref_name == 'main' && 'production' || 'development' }}
        run: |
          pnpm --filter @portfolio/public-tanstack-start... run build

      - name: Deploy
        working-directory: apps/public-tanstack-start
        run: pnpm run deploy:cloudflare "${{ github.sha }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Purge Cloudflare Cache (production)
        if: ${{ github.ref_name == 'main' }}
        uses: nathanvaughn/actions-cloudflare-purge@v4.0.0
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cf_auth: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          hosts: i-am.hokkyss.com
      
      - name: Purge Cloudflare Cache (development)
        if: ${{ github.ref_name == 'dev' }}
        uses: nathanvaughn/actions-cloudflare-purge@v4.0.0
        with:
          cf_zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          cf_auth: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          hosts: dev.hokkyss.com
